### PR TITLE
Add short Microsoft Windows section

### PR DESCRIPTION
**Pull request by dspinellis**

### CODE REVIEW

**Comment by jlevy** [comment]
Welcome addition, thanks! Definitely willing to include a section like this.

How about we call it "Windows only"? I'd like to clarify that other items *may* apply to Windows, but that the OS X and Windows sections are for items that only work on that platform.

Secondly, I'm not a Windows user so would appreciate any review/feedback on this section from one or two more die-hard Windows folks!

**Comment by dspinellis** [comment]
OK, I agree with a "Windows only" title. It matches the OS X section.  I didn't use it, because the section was broader, proposing the use of Cygwin.

**Comment by cstanhope** [comment]
I use Windows and Cygwin daily, so I hope my review will be useful. I took a quick glance through the rest of the document, and I don't see anything that doesn't also apply to Cygwin. So I think it is safe to include the Cygwin specific section. I have two suggestions:

 1. Add a link to the Cygwin site. I know people can search for it, but sometimes searching can lead people astray. A direct link would avoid that. (Although I realize the OS X section doesn't link to homebrew.)
 2. Perhaps a quick warning that under Cygwin there is a mapping of the posix filesystem to the Windows system. New users may want to see the documentation for an explanation.

But even without those changes, I think this an excellent addition to the document. I even learned something (about /dev/clipboard) even though I've been using Cygwin for years!

**Comment by jlevy** [comment]
@cstanhope thanks for the feedback.

Links are very welcome. The lack of links is entirely due to laziness on my part. I can think of no reason to avoid (helpful and stable) links. More should be present for OS X, Windows, and throughout the doc, actually.

**Comment by dspinellis** [comment]
@jlevy Thank you for the clarification regarding links. I was wondering whether this was a matter of style.

**Comment by jlevy** [comment]
Great. Since we've requested feedback, I'll leave this one open for another day in case there is anything else, and then merge in.

**Comment by JasonCoombs** [comment]
I'd like to review and comment but need a few days, if you'll leave this open a little longer. Thanks.

**Comment by dspinellis** [comment]
@cstanhope Thank you for the feedback. I incorporated the changes you suggested in 448887b781cdf5ae6ddb9108e07e4ad37ee93ce2.
@JasonCoombs Thank you for volunteering. I'm happy to wait.

**Comment by cstanhope** [comment]
@dspinellis Your changes address my suggestions. Looks good!

**Comment by jlevy** [comment]
@JasonCoombs will you still review?

**Comment by JasonCoombs** [comment]
Working on a write-up of suggestions today. Thanks for your patience.

**Comment by JasonCoombs** [comment]
I'm still working on this, but please everyone see my request for discussion, here: https://github.com/jlevy/the-art-of-command-line/issues/165#issuecomment-180076846

**Comment by jlevy** [comment]
Thanks for the discussion (will follow up more there shortly).

I believe this is a solid addition, and doesn't preclude expansion or improvement, so have merged it in.

Thank you @dspinellis ! And @JasonCoombs and @cstanhope for the comments.

**Pull request merged**
