### PR TITLE
Add instructions to manage filenames with whitespaces

### PR DESCRIPTION
**Pull request by uggla**
Whitespaces into filenames can be really painful to manage, especially on Linux cifs shares provided to windows users.
So these instructions to give some hints to manage them.

### CODE REVIEW

**Comment by neil-greenwood** [comment]
Also, a small typo in the word 'patern' - should be 'pattern'

**Comment by uggla** [comment]
@jlevy, I will add a commit in this way ASAP. However feel free to reword the way you like.
@neil-greenwood, thank you I will fix that in the next commit.

**Comment by uggla** [comment]
@jlevy, I have updated the sentence according to your suggestion. I'm not completely satisfy by the remaining part but right now I don't know how to improve and keep it short.
I'm open to your suggestion. Of course if you want to merge and modify it your own way, feel free to do it.

**Comment by jlevy** [comment]
:+1: Thanks. With those edits think we're good. Lmk if you see any issues.

**Comment by uggla** [comment]
:+1:

**Pull request merged**
