### PR TITLE
zh: Update Chinese translation in introductory paragraph

### PR DESCRIPTION
**Pull request by bryandeng**
> Fluency on the command line is **a skill** often neglected or considered arcane,

Add the missing translation for "**a skill**".

### CODE REVIEW

**Comment by bryandeng** [comment]
@Psycho7

**Comment by Psycho7** [comment]
#110 已经有一样的了...不过还木有merged sorry

**Comment by bryandeng** [comment]
唔，https://github.com/jlevy/the-art-of-command-line/pull/110 第一段修改的翻译是错误的。

https://github.com/jlevy/the-art-of-command-line/pull/110 不能 merge 是因为他在自己的 master 上干活，这时上游的 master 有新 commit 的话就冲突了。所以一定要新建一个 branch 再贡献代码。

先 merge 我这个吧，这两天再贡献些。

**Comment by Psycho7** [comment]
确实...没注意看 #110 里的语法有问题

**Comment by Psycho7** [comment]
@jlevy This can be merged :+1: 
There's a error in #110

**Comment by Psycho7** [comment]
不管怎么样 多谢指教了
我还是个小菜鸟 很多地方都得向各位请教 :)

**Comment by jlevy** [comment]
@Psycho7 can you say "@jlevy ready to merge" on ones you think a ready? Not sure which are and which conflict.

**Comment by Psycho7** [comment]
Sorry for that @jlevy 
I think this one can be closed

**Comment by bryandeng** [comment]
@Psycho7 Yes, you can merge https://github.com/jlevy/the-art-of-command-line/pull/128 instead.

**Comment by Psycho7** [comment]
Sorry for that

**Pull request closed without merging**
