### PR TITLE
Track and acknowledge authors.

### PR DESCRIPTION
**Pull request by jlevy**
This is my best effort at tracking roles from GitHub history,
and assembling them with a new script, "ghizmo assemble-authors".
Please let me know if you've been missed!

### CODE REVIEW

**Comment by jlevy** [comment]
I've finally had a chance to catch up on this task, as I've felt the this guide has been the result of great contributions from many people.

Please review and let me know of any omissions or inaccuracies here, and if maintainer roles are current.

Thank you everyone! 

@olegberman @ceoaliongroo @niltonvasques @peterkokot @Psycho7
@Ungsik-Yun @xuchunyang @spmbt @ujuc @BishopWolf @aaossa @Snowcat8436
@aneasystone @jalanb @Armour @daveloyall @grigory-rechistov @shukitchan
@kostya13 @michaelbarlow7 @stevenlordiam @vcvpaiva @zackp30 @delucks
@grossws @kesu @rajuvindane @cabreraalex @youmee @bsnux @hastinbe
@augmentedfourth @bj1 @csvoss @chriskuehl @crr0004 @ColasBroux
@kalgynirae @cmr @Deborah-Digges @danylevskyi @vndmtrx @StreakyCobra
@fazlearefin @morenoh149 @Hunter-Github @isegal @jsight @unixorn
@jtraub @matjaz @mayra-cabrera @xaionaro @landgraf @ahmetalpbalkan
@RasmusWL @saksham0808 @analogue @simar7 @SohamChakraborty @hunkim
@gitter-badger @EaterOA @kalbasit @zxdvd @danasmera @dimapaloskin
@githubashto @kargakis @kastian @osmero @p12se @taxusyew

**Comment by peterkokot** [comment]
Very nice. :+1:

**Comment by zackp30** [comment]
Thanks! :smiley:

**Comment by Armour** [comment]
Thanks~

**Comment by stevenlordiam** [comment]
Thanks! :+1:

**Comment by olegberman** [comment]
Thank you! 😌

**Comment by unixorn** [comment]
Thanks!

**Comment by csvoss** [comment]
Thanks!

**Comment by grossws** [comment]
Thanks :+1:

**Comment by Psycho7** [comment]
Thanks :+1:

**Comment by fazlearefin** [comment]
Very nice! Great success!!!￼ :+1::+1:

**Comment by ceoaliongroo** [comment]
Thanks! Great project and great team...

**Comment by crr0004** [comment]
Cheers, I link to this a lot when teaching people bash.

**Comment by rajuvindane** [comment]
On बुधवार 30 सप्टेंबर 2015 02:07 म.नं., Joshua Levy wrote:
> I've finally had a chance to catch up on this task, as I've felt the
> this guide has been the result of great contributions from many people.
> 
> Please review and let me know of any omissions or inaccuracies here, and
> if maintainer roles are current.
> 
> Thank you everyone!
> 
> @olegberman <https://github.com/olegberman> @ceoaliongroo
> <https://github.com/ceoaliongroo> @niltonvasques
> <https://github.com/niltonvasques> @peterkokot
> <https://github.com/peterkokot> @Psycho7 <https://github.com/Psycho7>
> @Ungsik-Yun <https://github.com/Ungsik-Yun> @xuchunyang
> <https://github.com/xuchunyang> @spmbt <https://github.com/spmbt> @ujuc
> <https://github.com/ujuc> @BishopWolf <https://github.com/BishopWolf>
> @aaossa <https://github.com/aaossa> @Snowcat8436
> <https://github.com/Snowcat8436>
> @aneasystone <https://github.com/aneasystone> @jalanb
> <https://github.com/jalanb> @Armour <https://github.com/Armour>
> @daveloyall <https://github.com/daveloyall> @grigory-rechistov
> <https://github.com/grigory-rechistov> @shukitchan
> <https://github.com/shukitchan>
> @kostya13 <https://github.com/kostya13> @michaelbarlow7
> <https://github.com/michaelbarlow7> @stevenlordiam
> <https://github.com/stevenlordiam> @vcvpaiva
> <https://github.com/vcvpaiva> @zackp30 <https://github.com/zackp30>
> @delucks <https://github.com/delucks>
> @grossws <https://github.com/grossws> @kesu <https://github.com/kesu>
> @rajuvindane <https://github.com/rajuvindane> @cabreraalex
> <https://github.com/cabreraalex> @youmee <https://github.com/youmee>
> @bsnux <https://github.com/bsnux> @hastinbe <https://github.com/hastinbe>
> @augmentedfourth <https://github.com/augmentedfourth> @bj1
> <https://github.com/bj1> @csvoss <https://github.com/csvoss> @chriskuehl
> <https://github.com/chriskuehl> @crr0004 <https://github.com/crr0004>
> @ColasBroux <https://github.com/ColasBroux>
> @kalgynirae <https://github.com/kalgynirae> @cmr
> <https://github.com/cmr> @Deborah-Digges
> <https://github.com/Deborah-Digges> @danylevskyi
> <https://github.com/danylevskyi> @vndmtrx <https://github.com/vndmtrx>
> @StreakyCobra <https://github.com/StreakyCobra>
> @fazlearefin <https://github.com/fazlearefin> @morenoh149
> <https://github.com/morenoh149> @Hunter-Github
> <https://github.com/Hunter-Github> @isegal <https://github.com/isegal>
> @jsight <https://github.com/jsight> @unixorn <https://github.com/unixorn>
> @jtraub <https://github.com/jtraub> @matjaz @mayra-cabrera @xaionaro
> @landgraf @ahmetalpbalkan
> @RasmusWL @saksham0808 @analogue @simar7 @SohamChakraborty @hunkim
> @gitter-badger @EaterOA @kalbasit @zxdvd @danasmera @dimapaloskin
> @githubashto @kargakis @kastian @osmero @p12se @taxusyew

Thanks a lot for acknowledging. My contribution was very small, but
anyways I am happy with the credits.

**Comment by niltonvasques** [comment]
Thanks man! :+1: 
It's amazing see so many people, from everywhere working together \o/

**Comment by jlevy** [comment]
Yes. The feeling is mutual. It's a privilege to work with all of you to make something useful.

Also, many thanks to the maintainers of the translations -- I know it takes work, and appreciate if you can keep them current (and if you can't, help me find others who can).

It takes effort, but I'll keep putting in time regularly if you are willing to as well. Let's keep this document alive and always improving. :+1: :v:

**Comment by jlevy** [comment]
Japanese in place too now, thanks to @doublemarket 
#283

**Pull request merged**
