### PR TITLE
es: Improvements for 'es' translation 

### PR DESCRIPTION
**Pull request by mayra-cabrera**
Hello 

I've polished 'es' translation a little to make it more "spanish", hope you like it!. I'm also available if you need to maintain it as the English one evolves :)

### CODE REVIEW

**Comment by jlevy** [comment]
Thanks for the suggestions!

There is also #222 open. I'll defer to @ceoaliongroo on what and how to merge.

**Comment by ceoaliongroo** [comment]
@mayra-cabrera Great work, 

I really appreciate the effort. Together with @aaossa will review the next new revision of spanish translation.

Please, wait until i'll create a new brach to merge the revisions and check together.

**Comment by mayra-cabrera** [comment]
Sure @ceoaliongroo let me know if you need any help. 

Quick summary of what I did in the changes: 
- I changed some sentences so they can be understood in all the varieties of spanish
- I make it a little less formal by referencing the reader with "tú" and by changing some verbs to a spanish "informal mode" (but I'm not sure about this since the use "tú" and "usted" changes from region to region within each country.)
- Fixes punctuation by replacing some commas with periods.

**Comment by ceoaliongroo** [comment]
@mayra-cabrera @jlevy this pull request can be close in favor PR #229, includes this review.

**Pull request closed without merging**
