### PR TITLE
Italian translation here!

### PR DESCRIPTION
**Pull request by francescomalatesta**
As the title says... I loved the original english version, so I decided to translate it in my language :)

### CODE REVIEW

**Comment by jlevy** [comment]
:+1: Thank you. Are you willing to be the Italian maintainer, as well?

**Comment by francescomalatesta** [comment]
Yes, it's fine for me :)

**Comment by jlevy** [comment]
Awesome! You're now officially the maintainer of Italian. :)
Thanks so much @francescomalatesta !

By the way, the commits at https://github.com/jlevy/the-art-of-command-line/commits/master doesn't link to your account for some reason, so your name isn't showing up as a contributor in the script I use to generate https://github.com/jlevy/the-art-of-command-line/blob/master/AUTHORS.md
I can override manually but might want to look at why that is -- perhaps an account setting or email address mismatch?

**Comment by massenz** [comment]
Excellent translation!
Grande @francescomalatesta :+1:

**Comment by francescomalatesta** [comment]
Thanks @massenz :D

**Pull request merged**
