### PR TITLE
zh: change some words

### PR DESCRIPTION
**Pull request by taxusyew**

### CODE REVIEW

**Comment by jlevy** [comment]
:+1: thanks! @Psycho7 review?

**Comment by Psycho7** [comment]
Okay

**Comment by jlevy** [comment]
@taxusyew Some other changes went in earlier. Could you please merge again?

**Comment by jlevy** [comment]
Or @Psycho7 ?

**Comment by Psycho7** [comment]
I dont know what to do...Not familiar with Git and Github
Should I create a new PR?

**Comment by jlevy** [comment]
Click "Use the command line" under "We can't automatically merge this pull request" for instructions. It's a little tricky the first time but good to know.

Or if you can do it @taxusyew let us know.

**Comment by Psycho7** [comment]
Eh...I cant find "Use the command line" or "We can't automatically merge this pull request" either.
There only are "This pull request contains merge conflicts that must be resolved." and "Only those with write access to this repository can merge pull requests."

It seems that I cannot resolve the conflicts.

**Comment by jlevy** [comment]
If @taxusyew does it it will be in this PR.

Otherwise you can add taxusyew's repo as a remote (https://help.github.com/articles/adding-a-remote/ ) and merge in the changes into a new PR and resolve the conflicts ( https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/ ).

Or, just make the changes yourself in a new PR.

**Comment by Psycho7** [comment]
There is a error in line 17.

**Comment by taxusyew** [comment]
Sorry I'm late. What can I do to fix this?

**Comment by Psycho7** [comment]
额...我不知道如何用英文描述
`熟练使用命令行是一种常常被忽视的技能或被认为是晦涩难懂的`里面有点语法错误，`常常被忽视的技能`是名词，然而和他并列的`晦涩难懂的`是形容词，两个不同词性的东西并列在一起似乎有些奇怪。

然后你在17行里进行的更改已经在#128 里被修改了。
而221行里的我当时翻译时是想把他翻译的有趣点，如果你认为那样不好的话就再提交个PR吧 :smile:

**Comment by taxusyew** [comment]
我是感觉形容一个东西”是更潮流的“有点怪怪的，因为”潮流“也是名词哦:blush:
感觉更新、更潮、更现代，都可以，哈哈

**Comment by Psycho7** [comment]
额...确实是，之前没注意到
改成`更潮`的如何？你交个PR吧 :smiley:

**Comment by taxusyew** [comment]
恩，好的，那就改成`更潮`吧 :blush:

**Comment by taxusyew** [comment]
just give up this pull request.

**Comment by xuchunyang** [comment]
So please close it by the way.

**Comment by Psycho7** [comment]
@jlevy merge this 😏

**Comment by xuchunyang** [comment]
> @jlevy merge this 😏

Why? @taxusyew Could you please close this PR?

**Comment by Psycho7** [comment]
sorry...i didn't see what he said
@taxusyew close this thx

**Pull request closed without merging**
