### PR TITLE
zh: Add Chinese translation for Mac only section

### PR DESCRIPTION
**Pull request by stevenlordiam**
Add Chinese translation for Mac only section and fixed some translation error

### CODE REVIEW

**Comment by jlevy** [comment]
Thank you!
@Psycho7 care to review?

**Comment by Psycho7** [comment]
Replacing all the half-width punctuation marks with their full-width alternatives and adding a half-width space between English and Chinese words would be better :)

See #133 for details

**Comment by stevenlordiam** [comment]
@Psycho7  thanks for pointing it out, I have made the required change to this section

**Comment by Psycho7** [comment]
@jlevy you can merge it now :)

**Comment by jlevy** [comment]
:+1: Great.

**Pull request merged**
