### PR TITLE
README-zh.md: Use Full-width comma and fix typos

### PR DESCRIPTION
**Pull request by xuchunyang**
This change is made with GNU sed by using:

     gsed --in-place 's/,/，/g' README-zh.md
     gsed --in-place 's/， /，/g' README-zh.md

### CODE REVIEW

**Comment by xuchunyang** [comment]
@Psycho7 Please review this when you have time since you are the maintainer of README-zh.md

**Comment by Psycho7** [comment]
Can be merged @jlevy 
But he do the same thing in line 63 as #111

**Comment by xuchunyang** [comment]
Well, I didn't notice that. You guys can merge my PR and close #111, or apply #111 first then merge this PR manually to regard @lkxiaolou's work.

**Comment by jlevy** [comment]
Thanks @xuchunyang for the suggestions and the review @Psycho7.

**Pull request merged**
