### PR TITLE
ko: Correct spelling

### PR DESCRIPTION
**Pull request by hyojin**
Correct Korean spelling

오타수정했습니다

### CODE REVIEW

**Comment by marocchino** [comment]
:+1:

**Comment by jlevy** [comment]
:+1: Thank you!
@Ungsik-Yun I'll merge as is?

**Comment by Ungsik-Yun** [comment]
@jlevy Yes! you can merge this :)

**Comment by jlevy** [comment]
Thanks @hyojin @marocchino !
Thanks @Ungsik-Yun -- hope you can keep reviewing the Korean PRs/issues!

**Pull request merged**
