### PR TITLE
zh: README-zh.md: Trivial improvements

### PR DESCRIPTION
**Pull request by xuchunyang**

### CODE REVIEW

**Comment by xuchunyang** [comment]
@Psycho7 I made some small fixes in `README-zh.md` to make the Chinese translation more fluent. Please take your time to review it.

**Comment by Psycho7** [comment]
Line 22
Should issue/PR be in plural form? I dont know whether it should be in plural form when English and Chinese are mixed.

Line 169
很多人都会使用`cut`，但几乎都不会使用`join`
Maybe this can be better?

**Comment by xuchunyang** [comment]
I applied your two suggestions and force-pushed. Thanks for the review.

**Comment by Psycho7** [comment]
@jlevy merge this

**Comment by jlevy** [comment]
:+1:

**Pull request merged**
