### PR TITLE
Python confirm

### PR DESCRIPTION
**Pull request by NewAlexandria**
1. Incorporated @nicolaszrak note about Python 3 (from #49).
1. Added a confirmation step for Python version.
3. [proposed] formatting for the group.

### CODE REVIEW

**Comment by nicolasazrak** [comment]
+1

**Comment by Graham42** [comment]
I'm pretty sure it's a capital V for version, lowercase v starts Python on verbose mode

**Comment by NewAlexandria** [comment]
so it is

**Comment by jlevy** [comment]
Fixed in briefer form in another PR. But thanks!

**Pull request closed without merging**
