### PR TITLE
pt: Fixups

### PR DESCRIPTION
**Pull request by theuves**

### CODE REVIEW

**Comment by jlevy** [comment]
Thanks. @niltonvasques review?

**Comment by theuves** [comment]
:smiley:

**Comment by theuves** [comment]
@niltonvasques veja: [Afinal, qual é o plural de item?](http://linguamodadoisec.blogspot.com.br/2009/12/afinal-qual-e-o-plural-de-item.html)

**Comment by jlevy** [comment]
@niltonvasques ping?
Or @theuves would you review?

**Comment by niltonvasques** [comment]
@jlevy The pull request #433 is more complete than this. So I recommend close it, because the other is a better replacement.

**Comment by niltonvasques** [comment]
@theuves Thanks man!

**Comment by theuves** [comment]
@niltonvasques :v:

**Comment by jlevy** [comment]
Thanks @theuves! Comments on #433 or more PRs always welcome.

**Pull request closed without merging**
