### PR TITLE
el: Greek translation and maintainer

### PR DESCRIPTION
**Pull request by anna-d**
#365

### CODE REVIEW

**Comment by jlevy** [comment]
:+1: Great! Thank you @anna-d . Are you also willing to be Greek maintainer?

Would also like at least one review from another native Greek speaker, if we can find one.

@dspinellis perhaps you have time? Or another volunteer?

**Comment by anna-d** [comment]
@jlevy  yes

**Comment by dspinellis** [comment]
Yes, I will review it. @anna-d for the sake of efficiency, I will open a pull request with changes.

**Comment by anna-d** [comment]
@jlevy  you can merge

**Comment by jlevy** [comment]
Thank you @anna-d @dspinellis -- this is now linked in.

**Pull request merged**
