### PR TITLE
[uk] Replace дебаггінг -> відладка.

### PR DESCRIPTION
**Pull request by dmytro**
debugging: Use commonly used Ukrainian word instead of transliterated English.

### CODE REVIEW

**Comment by l13t** [comment]
I'm not linguist but from my point of view it's better to leave "Дебаггінг". Cause "Відладка" looks like copy-paste from Russian.

**Comment by dmytro** [comment]
I understand your point. I do like word 'відладка', but also see rationale in what you're saying. 

How would you like another word as a replacement for the 'дебаггінг': "зневадження"?  

https://goo.gl/PI5qir This is a reference to Ukrainian wikipedia page for debugging.

**Comment by dmytro** [comment]
Another small note. If it will be decided to keep word 'дебаггінг', its spelling should change a bit. 

According to the Ukrainian grammar, in a words borrowed from other languages consonants are not doubled. I.e. it should become: 'дебагінг'.

Please see for reference: http://linguana.com.ua/ukrayinska-mova/orfografiya/podvoyennya-prygolosnyh-u-slovah-inshomovnogo-pohodzhennya.html

**Comment by stepan0904** [comment]
I'm for Дебагінг
this is not very grammar but more understandable

**Comment by stepan0904** [comment]
@dmytro I don't have many time for continue support this translate
if you wont I can ask @jlevy set you as maintainer of Ukrain translate

(for now not translated **windows only** part)

**Comment by dmytro** [comment]
@stepan0904 
Thank you, please do so. I can support project going forward.

**Comment by stepan0904** [comment]
@jlevy add @dmytro like  maintainer
from hi will be responsible for Ukraine translate

and close this merge

**Comment by dmytro** [comment]
Hi @jlevy,

Nice meeting you. I hope I'll be helpful with the finishing and improving Ukrainian translation of the document. Maybe even with the contribution to the English version as well, as I am myself is a UNIX administrator with 15+ years of experience.

Regards,
Dmytro

**Comment by jlevy** [comment]
OK, thank you, @dmytro — appreciate you helping with this! I'll switch you to be the Ukrainian maintainer. New contributions are certainly welcome. And thanks @stepan0904 for your work.

**Pull request merged**
