### PR TITLE
Added example of the `column` command.

### PR DESCRIPTION
**Pull request by ShawnMilo**
This is really useful for viewing files on the command line.

### CODE REVIEW

**Comment by tim-teufel** [comment]
Seems the commit message is of the other one. :wink:

**Comment by ShawnMilo** [comment]
Oops, thanks. Fixed.

**Comment by Neirda24** [comment]
:+1:

**Comment by jlevy** [comment]
For sure, I'm in favor of adding this to the "Obscure but useful section".

In the interest of brevity, I don't want to include the full example input and output, but just one sentence that it adjusts lists to fixed-width columns is appropriate. Thanks!

**Comment by jlevy** [comment]
Ah, looking again, I see it's already there. I slightly expanded the wording to be clearer and think I'll leave it at that to keep things brief. Thanks again.

**Pull request closed without merging**
