### PR TITLE
Add new command : hexedit

### PR DESCRIPTION
**Pull request by mudongliang**
Add new command: hexedit and remove the redundancy

### CODE REVIEW

**Comment by jlevy** [comment]
Thanks. hexedit should be in the list of editors, however, right?

**Comment by mudongliang** [comment]
Yes, you're right! I was hurry at that time. I will change it!

2016-03-20 18:32 GMT-04:00 Joshua Levy <notifications@github.com>:

> Thanks. hexedit should be in the list of editors, however, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jlevy/the-art-of-command-line/pull/385#issuecomment-199049235>
>



-- 
My best regards to you.

     No System Is Safe!
     mudongliang

**Comment by mudongliang** [comment]
I have changed this `hexedit` to English, zh, zh-Hant version! However, the Chinese translation put editor and reader to one list, and not differ them. Should I differ them, @jlevy ?

**Comment by jlevy** [comment]
Yes, please keep this PR English only. That way, the Chinese maintainers can merge in all upstream changes when the translations are updated. Thanks!

**Comment by jlevy** [comment]
(You might find it easier to close and open a new PR without the extra commits.)

**Comment by mudongliang** [comment]
This PR only includes change to English version.

**Pull request closed without merging**
