### PR TITLE
zh: Add a half-width space between English and Chinese words

### LINKED ISSUE #126: zh: Proper spacing between English and Chinese words
When typesetting mixed English-Chinese text, it's suggested to add space between English and Chinese words. For example, `使用 Github 来做` instead of `使用Github来做`.

Reference: http://www.zhihu.com/question/19587406

### PR DESCRIPTION
**Pull request by xuchunyang**
I'm trying to fix #126 by adding a half-width space between English and Chinese manually, I've completed 14%, @Psycho7 do you think if these changes are acceptable? If I did it right, I will continue working on this.

### CODE REVIEW

**Comment by Psycho7** [comment]
Line 32
本文包括了"标准的" Unix 命令
2 spaces seems better than only one space in right side
What do you say?

Line 48
There‘s a extra 'a' in the end of line.

**Comment by xuchunyang** [comment]
> Line 32
> 本文包括了"标准的" Unix 命令
> 2 spaces seems better than only one space in right side
> What do you say?

I guess you meant adding a space in front of "Unix", I think it looks better but doesn't follow some rule pointed in #126 (i.e., http://www.zhihu.com/question/19587406):

> 中文正文及标题中出现的英文及数字应该使用半角方式输入，并且在左右各留一个半角空格。如果这些这些半角英文及数字的左边或者右边紧接着任何的中文全角括号或者其他标点符号的话，则不需要加入半角空格。

----
> Line 48
> There‘s a extra 'a' in the end of line.

Will fix.

**Comment by xuchunyang** [comment]
I've just finished this. @Psycho7 when you review these changes, you can use line comment as well It's easier for both of us.

**Comment by bryandeng** [comment]
Thanks! @xuchunyang

**Comment by Psycho7** [comment]
I think some rule pointed in #126 are not always suitable.

For example,
```
Line 425
Linux 发行版信息
```
"Linux发行版" is a whole word, and a space in the middle of it split up to 2 words. Some one who are not familiar with Linux may take it as `"Linux的发行版信息"` instead of `"Linux发行版的信息"`. I think it misleading. 
It seems okay in `Line 252` but I don't know the reason.
Can you get my point? Sorry for my unclear description.

And
```
Line 405
CPU 和硬盘状态

Line 429
包括 RAID、显卡等
```
'CPU' and '硬盘状态' are coordinate as well as 'RAID' and '显卡' in fact, but it looks weird now and not coordinate.
I think add more spaces will make it better. 
Like this
```
CPU 和 硬盘状态
包括 RAID、显卡 等
```

What do you guys say? @xuchunyang  @bryandeng

**Comment by xuchunyang** [comment]
Add space between English and Chinese (or not) doesn't change the real meaning, reader should not assume that, I guess `Linux发行版 信息` is clearer than `Linux 发行版信息` and `Linux发行版信息` but of course it is not acceptable, in other words, adding space between Chinese words is never acceptable, even it can looks better (readability and accuracy).

> I think some rule pointed in #126 are not always suitable.

If so, we should just say no to #126, we probably aren't Chinese experts and not qualified to make rules.

**Comment by bryandeng** [comment]
Just blindly add one half-width space between any pair of Chinese character and English letter.
Always use full-width punctuations. No need to add space between full-width punctuations and English letters.

**Comment by Psycho7** [comment]
Well...I prefer to add space between Chinese if it can improve readability, but I won't do it in formal occasions.

**Comment by Psycho7** [comment]
@bryandeng What do you mean? Just merge this PR without any modification or something?

**Comment by bryandeng** [comment]
@Psycho7 Adding space between Chinese characters should always be avoided.

**Comment by bryandeng** [comment]
@xuchunyang Can you replace all the half-width punctuation marks with their full-width alternatives? Now they are in mixed use.

**Comment by xuchunyang** [comment]
> @xuchunyang Can you replace all the half-width punctuation marks with their full-width alternatives? Now they are in mixed use.

I agree with you, except half-width space, we should try to use only full-width punctuation marks, but this  goes beyond this PR, all I have done here is adding one half-width space between Chinese and English text, nothing else. I think someone can fix it in another PR.

**Comment by Psycho7** [comment]
@jlevy ready to merge :)

**Comment by jlevy** [comment]
:+1: 
Does this close #126 ?

**Comment by bryandeng** [comment]
@jlevy Yes, this closes https://github.com/jlevy/the-art-of-command-line/issues/126.

**Comment by jlevy** [comment]
Awesome. Thanks everyone for the improvements!

**Pull request merged**
