### PR TITLE
en: Fix description of `env` and add description of `eval`

### PR DESCRIPTION
**Pull request by jjerphan**
**Main changes**: The description of `env` was the one of `eval`. It has been modified so that both appear correctly.

**About translations**: I can submit PRs for French, Spanish, Italian and German if this one is approved.

### CODE REVIEW

**Comment by jjerphan** [comment]
@Psycho7: I saw you are merging PRs. Can you have a look at this one, please? Thank you! :)

**Comment by jjerphan** [comment]
Hello @jlevy ; can you review this PR?
Thank you!

**Comment by jjerphan** [comment]
Hey @Psycho7, could this be merged? :)

**Comment by Psycho7** [comment]
Hi @jjerphan , I'm sorry I'm only the maintainer for ZH translation. And I don't even have the privilege to merge PRs... I'm sorry.

**Comment by jjerphan** [comment]
Hello,

No problem. It looks like @jlevy isn't active anymore :thinking:

**Comment by Psycho7** [comment]
I agree with you.

And you'll find this on the top of this repo.
> Note: I'm looking for a new (and potentially paid) lead author to help expand this to a more comprehensive Guide. While it's very popoular, it could be both deeper and more helpful. If you like to write and are close to being an expert on this material and willing to consider helping, please drop me a note at josh (0x40) holloway.com. –jlevy, Holloway

**Comment by jjerphan** [comment]
Hello @jlevy ?

**Pull request closed without merging**
