### PR TITLE
Consider onsgmls, pup, or other HTML parsers

### PR DESCRIPTION
**Pull request by uggla**

### CODE REVIEW

**Comment by jlevy** [comment]
I'm not sure SGML is common enough anymore to merit mention.
If there's anything current/unique about this tool's handling of HTML, please comment though.
Thanks!

**Comment by uggla** [comment]
Hello Joshua,

In fact onsgmls parses html which is better, simpler than using regex to do it.
Note :  Doing a full html parser is a tricky stuff, so relying on a good parser can save a lot of time.

One example of usage, list html tags and count them.
```
[uggla@ugglalaptop ~]$ onsgmls index.html 2>&- | sed -n -e 's/^(//p' | sort | uniq -c
    534 A
      1 ABBR
     16 ARTICLE
      2 ASIDE
      1 BODY
      4 BR
      ....
```
I let you judge if it makes sens to include it or not. Of course this is not something you will use on a daily basis so maybe out of scope for the-art-of-command-line.

**Comment by jlevy** [comment]
OK. I think there is a need for mention of a better general HTML parser that handles messy HTML.

Another example: https://github.com/EricChiang/pup

Reopening to let us discuss/assemble any other options.

**Comment by uggla** [comment]
Hello @jlevy,

I did not know about pup, looks interesting.

>I think there is a need for mention of a better general command-line HTML parser that handles messy HTML and common tasks

I think it is interesting to highlight people that using a parser is most of the time a efficient solution to validate and manipulate json, html, xml etc...

Regarding onsgmls, this is larger than html.
onsgmls / nsgmls is part of OpenSP (http://www.jclark.com/sp/).
I think it is a really reliable set of tools, that strictly respects standards.
It can be used to validate/parse sgml, so xml, html, docbook which are subsets of sgml.

**Comment by derimagia** [comment]
Thanks for the mention of sp @uggla. I downloaded open-sp through brew and it seems to be a big buggy which is a shame. It doesn't look what I want though since I don't see ways to just modify a stream of html in a way similar to jq. I don't want a another markup language. 

I have used pup before and that will continue to be my go-to for html. For json there's jq and for xml/html there isn't something thats at the same level as it but I think pup does what I need most of the time. I liked the github repo https://github.com/dbohdan/structured-text-tools#xml-html which has some good mentions.

**Comment by uggla** [comment]
@derimagia, to be completely honest, I don't use the shell if it becomes it  bit "complex". For html I use python and Beautiful Soup. For xml I use python as well with ElementTree.

**Comment by NilsIrl** [comment]
I've never used it but [hxextract](https://www.w3.org/Tools/HTML-XML-utils/man1/hxextract.html) seems to be another option.

The tool is under the html-xml-utils package on some distros. This package also includes [many other tools](https://www.w3.org/Tools/HTML-XML-utils/README).

**Pull request closed without merging**
