### PR TITLE
fr: Add french translation

### PR DESCRIPTION
**Pull request by ericguirbal**
Hi,

It's a full translation. French is my mother tongue.

### CODE REVIEW

**Comment by rverchere** [comment]
Arff, dommage...

Is you translation complete? You can maybe check your work with ours here to make other improvements here: https://mypads.framapad.org/p/the-art-of-command-line-l5duq74l

**Comment by ericguirbal** [comment]
Yes, it is complete, but I have no doubt it could be better. I send an email to the Framalang mailing list to put the practical details in place.

**Comment by jlevy** [comment]
:+1: Thank you. This is great progress.

Can another French speaker review the current version? If quality is high, we can merge soon. If it needs some improvements, let's keep updating this PR since it is recent and mostly complete.

**Comment by jlevy** [comment]
@rverchere thanks for the efforts as well! Can any improvements be merged in here? It should be possible to PR into https://github.com/ericguirbal/the-art-of-command-line/tree/fr

**Comment by uggla** [comment]
Hello Joshua,

I have read the translation from @ericguirbal, that looks good to me. I think this can be merged as a first French translation. So people will have something to work on and improve with PR.

**Comment by jlevy** [comment]
:+1: Great. Thank you @ericguirbal @rverchere @uggla and everyone who's helped get us toward a French translation! Merged.

Translations are always a collaborative effort from several people. But I do think it's important to have one person listed as primary "maintainer" of French: https://github.com/jlevy/the-art-of-command-line/blob/master/CONTRIBUTING.md#translations

@ericguirbal since you're the first to have completed the entire thing work: Are you willing to be maintainer as well?

**Comment by jlevy** [comment]
Please also keep giving feedback/PRs on the translation. See #351 too.

**Comment by ericguirbal** [comment]
> @ericguirbal since you're the first to have completed the entire thing work: Are you willing to be maintainer as well?

Yes. Thank you @jlevy for your confidence.

**Pull request merged**
