### PR TITLE
zh: traditional/simplified labels

### PR DESCRIPTION
**Pull request by mudongliang**

### CODE REVIEW

**Comment by jlevy** [comment]
Thanks!
If we do change this, it should be changed on all files, however.
@Psycho7 @kevingo review?

**Comment by kevingo** [comment]
Sure, I will check it later.

**Comment by kevingo** [comment]
The modified is ok for me, however, it should be applied on all files.

**Comment by Psycho7** [comment]
Agree with @kevingo 
Obviously, it should be applied on all files not only README.md

**Comment by jlevy** [comment]
@mudongliang could you make the same change on all files?

**Comment by mudongliang** [comment]
@jlevy I've changed all the files. Is it OK?

**Comment by kevingo** [comment]
LGTM :+1:

**Comment by jlevy** [comment]
Thanks @mudongliang and @kevingo @Psycho7 !

**Pull request merged**
