### PR TITLE
zh: Change some mouthful of words in chinese

### PR DESCRIPTION
**Pull request by w169q169**

### CODE REVIEW

**Comment by Psycho7** [comment]
Everything is fine except the style in line 90. Plz keep the style consistent with others. See #133.

Anyway, appreciate what you have done. :)

**Comment by Psycho7** [comment]
Plus, a proper prefix like 'zh: ' to the title would be better for other people to review.

**Comment by w169q169** [comment]
@Psycho7 Many thanks for your help. I will change these style problems in another commit.

**Comment by Psycho7** [comment]
@w169q169 :+1: 

@jlevy Can be merged

**Comment by jlevy** [comment]
:+1: Thanks!

**Pull request merged**
