### PR TITLE
zh: Sync with the English version, line by line

### PR DESCRIPTION
**Pull request by wyf88**

### CODE REVIEW

**Comment by Psycho7** [comment]
Thank you for ur fabulous work :+1: 
@jlevy Just merge it :smile:

**Comment by wyf88** [comment]
@Psycho7  Thanks. Please feel free to refine my translations, I'm never good at languages :sweat_smile:

**Comment by Psycho7** [comment]
@wyf88 Don't say that. It seems you are far better than me in language competence :)

**Comment by jlevy** [comment]
:+1: Thanks to you both!

**Comment by wyf88** [comment]
Hmmm, the link of "Windows only" section does not seem to work. @Psycho7 Can you help me to take a look? Thanks!

**Comment by Psycho7** [comment]
@wyd88 There are spaces between chars, so the link should use dash replacing space. Like this "#仅限-Windows-系统". However my computer is not at my hand right now... So i'm not sure if it works.
Anyway, you can look at the link to *OS X only* for hint. I remember I encountered the same problem before.

**Comment by wyf88** [comment]
@Psycho7 Thanks! I will try that later.

**Pull request merged**
