### PR TITLE
zh-Hant: Correct markup effect in README-zh-Hant.md

### PR DESCRIPTION
**Pull request by fbukevin**
Change "**enter **" to " **enter**" for correcting the markup effect.

### CODE REVIEW

**Comment by rotvulpix** [comment]
LGTM

**Comment by Psycho7** [comment]
LGTM @kevingo

Add a prefix `zh-Hant` in this case would help maintainers to do review.

**Comment by kevingo** [comment]
LGTM :)

**Comment by jlevy** [comment]
👍 Thanks all!

**Pull request merged**
