### PR TITLE
ru: sync&correct translate

### PR DESCRIPTION
**Pull request by 0xCD**
Complete sync with original.

### CODE REVIEW

**Comment by jlevy** [comment]
@olegberman review?

**Comment by olegberman** [comment]
Sure, will do after work. :)

**Comment by jlevy** [comment]
:+1: thanks as usual. :)

**Comment by 0xCD** [comment]
Bump.

**Comment by olegberman** [comment]
These are useful changes. @jlevy you can merge.

**Comment by jlevy** [comment]
:+1: Thanks @0xCD and @olegberman !

**Pull request merged**
