### PR TITLE
es: Grammar and orthography checks

### PR DESCRIPTION
**Pull request by BishopWolf**
Some corrections to the spanish version

### CODE REVIEW

**Comment by jlevy** [comment]
Looks like you're still improving this? I'll check back end of day -- ping me when you both think it's ready. :) Thanks so much for improving it!

**Comment by ceoaliongroo** [comment]
@BishopWolf for you, is ready to merge?

for me it's ready!

**Comment by BishopWolf** [comment]
yes, it is ready for me, sorry for the delayed answer

**Comment by jlevy** [comment]
:+1: :+1: Thanks @BishopWolf @ceoaliongroo

**Pull request merged**
