### PR TITLE
Indonesian (ID) translation

### PR DESCRIPTION
**Pull request by 23Pstars**

### CODE REVIEW

**Comment by jlevy** [comment]
Great. @23Pstars is it ready to merge? And are you able to maintain it? If so I'll mark you as maintainer of this translation.
@mkwardakov thanks for reviewing; you are fluent and it looks good?

**Comment by jlevy** [comment]
Many thanks! :)

**Comment by 23Pstars** [comment]
@jlevy yes :)

**Comment by jlevy** [comment]
👍 @23Pstars Thank you! Merged. You are now Indonesian maintainer. :) Thanks @mkwardakov as well.

**Pull request merged**
