### PR TITLE
Small documentation update.

### PR DESCRIPTION
**Pull request by uggla**
Hello,

Small update about various things (see below).

Update documentation with the following changes :
-Add flow control information.
-Add byobu information.
-Add onsgmls and Xpath information.

Feel free to rework the way you like.

### CODE REVIEW

**Comment by jlevy** [comment]
These are some useful tips. In particular `sdiff` and `vimdiff` look good, but I'm not sure about the others without a bit more thought -- could you can separate them out into different PRs?

**Comment by uggla** [comment]
Hello Joshua,

I have created another pull request #259 with only the sdiff and vimdiff info, so I think you can fast forward merge it into your master branch.

Regarding the other info, I let you think/decide what you want to add or not. Let me know if others pull requests are required.
To give a couple of arguments to have them included : 
- The ESC-v in vi mode is not well known but really useful to manipulate long command strings.
- tr is simple and efficient.
- Xpath is pretty cool to query xml. ;)   (Not to influence you... :) )

**Comment by uggla** [comment]
Hello Jushua,

I have split all the changes into individual pull requests :

**Comment by jlevy** [comment]
Thank you! Closing this and will review them.

**Pull request closed without merging**
