### PR TITLE
(macos) adds mdls to "obscure but useful commands"

### PR DESCRIPTION
**Pull request by wingsuitist**
mdls lists metdata of all kind of files like
thx to: http://www.askdavetaylor.com/can-i-analyze-exif-information-on-the-mac-os-x-command-line/

### CODE REVIEW

**Comment by jlevy** [comment]
Good suggestion, but MacOS only. I'm going to mark these and if we get enough will consider a MacOS section or similar. This guide was written so that all commands work on Linux. Thanks!

**Comment by wingsuitist** [comment]
Thank you for your work and feedback! What about packages that can be installed on most linux and on osx with homebrew? Like ffmpeg?

**Comment by jlevy** [comment]
All the commands work on Linux and most of the commands in the guide are installable via brew etc. (see the scope section).

**Comment by jlevy** [comment]
Moved this into #153. Will address all those at once.

**Pull request closed without merging**
