### PR TITLE
Excuting a script file

### PR DESCRIPTION
**Pull request by aneasystone**
For executing a script file, you could use `sh script-filename` or `./script-filename` or `source script-filename` or `. script-filename`. The following are the differences:

 - `./script-filename` is identical to `sh script-filename`, excepting the script file should has execute permission, and the commands executed are in a subshell.
 - `source script-filename` executes the script file within the current context.
 - `. script-filename` is alias to `source script-filename`

Hope this is useful.

### CODE REVIEW

**Comment by ShawnMilo** [comment]
I think this should briefly cover `$PATH` as well, for completeness. Specifically that adding a directory, even a relative one, such as `.`, to your `$PATH` environment variable gives you yet another way to execute a script. Also, mention `chmod +x` to make a script executable for all of those methods other than `sh filename`.

**Comment by jlevy** [comment]
Reflecting on this, I still don't think this is clear enough and that we should split these out as two adjacent bullet points: #261 and #262 
Open to PRs on those individually.
Thanks to you both for the suggestions/discussion!

**Comment by aneasystone** [comment]
@jlevy Sorry for my poor English and unclear statements, I just commit two individual PRs #268 & #269 , you can check it there, and many thanks for this excellent project !

**Comment by matt-kita** [comment]
> For executing a script file, you could use `sh script-filename` or `./script-filename` or `source script-filename` or `. script-filename`. The following are the differences:
> 
> * `./script-filename` is identical to `sh script-filename`, excepting the script file should has execute permission, and the commands executed are in a subshell.

Well, not exactly correct. While the 'sh script-filename' mentions explicitly, that the script should be executed by whatever shell the 'sh' is currently pointing to, the './script-file' will execute the script in either: the child process (subshell) of your current shell; or in whichever shell that a "Shebang" line is correctly pointing to.

**Comment by matt-kita** [comment]
> For executing a script file, you could use `sh script-filename` or `./script-filename` or `source script-filename` or `. script-filename`. The following are the differences:
> 
> * `./script-filename` is identical to `sh script-filename`, excepting the script file should has execute permission, and the commands executed are in a subshell.

Well, not exactly correct. While the 'sh script-filename' mentions explicitly, that the script should be executed by whatever shell the 'sh' is currently pointing to, the './script-file' will execute the script in either: the child process (subshell) of your current shell; or in whichever shell a "shebang" line is correctly pointing to (if the "shebang" line is present in the script).

**Pull request closed without merging**
