### PR TITLE
Fix #318: s/MacOS X/OS X

### LINKED ISSUE #318: 'MacOS X' should be 'OS X'
It was never called 'MacOS X' and 'Mac OS X' has been changed to 'OS X'.
https://en.wikipedia.org/wiki/OS_X

### PR DESCRIPTION
**Pull request by rileyjshaw**

### CODE REVIEW

**Comment by peterkokot** [comment]
:+1: Yes, it probably should be only OS X. I would suggest also fixing links with correct anchors... Thanks

**Comment by rileyjshaw** [comment]
No problem. I just fixed and amended the initial commit :+1:

**Comment by ceoaliongroo** [comment]
:+1:

**Comment by jlevy** [comment]
:+1: Sure, thanks @rileyjshaw @peterkokot ! (I'm so old I'd not even noticed the name change was official.)

**Comment by louwers** [comment]
It's far from done though.

**Pull request merged**
