### PR TITLE
zh: Refinement

### PR DESCRIPTION
**Pull request by Psycho7**
Updated the content of Chinese version and refined it.

@jlevy Are you ready?

### CODE REVIEW

**Comment by jlevy** [comment]
@Psycho7 cool, thanks for the thorough redo! This is a big change. Glad to merge, but perhaps we should get one more native Chinese speaker to proof read before merging it in?

**Comment by Psycho7** [comment]
Well that's fine if you insist.

Perhaps @kevingo , the maintainer of traditional Chinese version, would like to do so.

**Comment by kevingo** [comment]
This version is more elegant and fluency, thanks @Psycho7. LGTM.

**Comment by jlevy** [comment]
👍 Great. Thanks again @Psycho7 ! And @kevingo for the additional review.

**Pull request merged**
