### PR TITLE
uk: Ukrainian translation

### PR DESCRIPTION
**Pull request by stepan0904**
+ Ukrainian translate

### CODE REVIEW

**Comment by jlevy** [comment]
Great! Are you also willing to maintain this translation? If so, we should add you as "translator and maintainer".

**Comment by jlevy** [comment]
Also: The ISO 2-letter language code for Ukrainian is "uk" (ua is the country code, but uk is what's used by Wikipedia and similar). See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes and https://en.wikipedia.org/wiki/List_of_Wikipedias#Detailed_list

Let's fix this, and also put it alphabetically in the languages lists, before "zh"?

Finally, the authors.md file is generated automatically (via "ghizmo assemble-authors") and -- so may not include your true name if your GitHub profile doesn't show it: https://github.com/stepan0904

Glad to merge it and make you maintainer if these can be fixed. Many thanks! :+1:

**Comment by stepan0904** [comment]
>Are you also willing to maintain this translation?
yes, sometimes
>language code for Ukrainian is "uk"
fixed
>include your true name if your GitHub profile
done

**Comment by jlevy** [comment]
:+1: Thank you! I'll also put you down as maintainer.

**Pull request merged**
