### PR TITLE
Add usage of `ps aux | grep <process>`

### PR DESCRIPTION
**Pull request by sriharshakappala**
This is one of the most famous ways to find the PID of a particular process. I was wondering till now no one has included it in this great document.

### CODE REVIEW

**Comment by 0xmohit** [comment]
I'd say that `pidof` would be better instead.

**Comment by neil-greenwood** [comment]
+1 for `pidof`

**Comment by sriharshakappala** [comment]
Yes, I agree it would be better. But won't it be difficult to figure out if there are a lot of processes with the similar name running? 

Correct me, if I am wrong here. Let's say, for example, the below command gives the entire list of processes with the name `postgres` and I can pick the pid of the process which I am interested in.

```bash
➜  ~ ps aux | grep postgres
postgres  1157  0.0  0.0 294656  3808 ?        Ss   10:46   0:00 postgres: checkpointer process   
postgres  1158  0.0  0.0 294656  5368 ?        Ss   10:46   0:00 postgres: writer process   
postgres  1159  0.0  0.0 294656  3808 ?        Ss   10:46   0:00 postgres: wal writer process   
postgres  1160  0.0  0.0 295084  6288 ?        Ss   10:46   0:00 postgres: autovacuum launcher process   
postgres  1161  0.0  0.0 149640  2936 ?        Ss   10:46   0:00 postgres: stats collector process   
postgres  1635  0.0  0.0 291272  6164 ?        Ss   10:46   0:00 postgres: checkpointer process   
postgres  1636  0.0  0.0 291140  5108 ?        Ss   10:46   0:00 postgres: writer process   
postgres  1637  0.0  0.0 291140  3856 ?        Ss   10:46   0:00 postgres: wal writer process   
postgres  1638  0.0  0.0 291992  6148 ?        Ss   10:46   0:00 postgres: autovacuum launcher process   
postgres  1639  0.0  0.0 147132  4024 ?        Ss   10:46   0:00 postgres: stats collector process   
```

But doing this, on the other hand, is like going into wild. 
```bash
➜  ~ pidof postgres
9097 9083 5746 1639 1638 1637 1636 1635 1161 1160 1159 1158 1157 957 956
```

**Comment by 0xmohit** [comment]
ps -p "$(pidof postgres)" w

Also see `pgrep`.

**Comment by yogesh-desai** [comment]
+1 for pidof

**Comment by jlevy** [comment]
Well, it was omitted deliberately, as it has a lot of corner case reasons it's brittle. If you're just looking for matches, `pgrep -f` is often a better option.

That said, we probably should elaborate. How about this as a new bullet point?

- To look up a process by name, use `pidof` (for exact matching) or `pgrep`. Use `pgrep -f` to search for processes and match the entire command line. (Combinations like `ps aux | grep ...` and similar can also be used for searching for processes interactively, but can have many corner-case failures and should be avoided for scripting.) Use `pkill` to kill processes by name.

**Comment by jlevy** [comment]
@sriharshakappala thanks for the addition, but I'm going to close this as the best bullet point would really mention all of these, as discussed.

@sakshamsharma @0xmohit @neil-greenwood @yogesh-desai do give your thoughts on #475 ? Thanks all!

**Pull request closed without merging**
