### PR TITLE
ja: Tweak the tone

### PR DESCRIPTION
**Pull request by m-takagi**
This pull request aligns the tone to informal style.

// 「です・ます」->「だ・である」

### CODE REVIEW

**Comment by jlevy** [comment]
Thank you!
@doublemarket review?

**Comment by mhayato** [comment]
Although I've decided to translate imparative forms in body into だ・である and others as addtional info into です・ます at the time but this seems better.
It's OK to merge @jlevy and thanks @m-takagi !

**Comment by jlevy** [comment]
:+1: Thanks to you both.

**Comment by doublemarket** [comment]
Oops, I mistakenly use my another account to comment. It's me! ;)

**Comment by jlevy** [comment]
I figured that out. Just please use the same original one to commit with, or author stats will be mixed up. ;)

**Pull request merged**
