### PR TITLE
ja: fixed Japanese kanji.

### PR DESCRIPTION
**Pull request by yasuhiroki**
This pull request fixes a kanji.

"遅れる" means, be delayed.
"送れる" means, can send.

### CODE REVIEW

**Comment by m-takagi** [comment]
:+1:

**Comment by jlevy** [comment]
:+1: Thank you!
@doublemarket I'll merge as is?

**Comment by mhayato** [comment]
@yasuhiroki Thanks for fixing! That's my misspelling.

@jlevy Yes, it's :ok:

**Comment by doublemarket** [comment]
@yasuhiroki Thanks for fixing! That's my misspelling.

@jlevy Yes, it's :ok:

**Comment by jlevy** [comment]
Thanks @yasuhiroki @m-takagi @doublemarket !

**Pull request merged**
