### PR TITLE
zh-Hant: Translate to Traditional Chinese

### PR DESCRIPTION
**Pull request by kevingo**
This is the first version of Traditional Chinese translation.

### CODE REVIEW

**Comment by jlevy** [comment]
Merged. Fixes #349 

Thanks @kevingo !

If anyone else (@Psycho7 ?) wishes to review and comment here or file new PRs, please do.

@kevingo you're now maintainer of traditional Chinese. Assume you can continue maintenance and review of everything on this translation. Thank you!

**Comment by kevingo** [comment]
@jlevy Thanks !

**Comment by Psycho7** [comment]
Well I'll be there if you guys need me 🙂
And thanks @kevingo 👍🏻

**Comment by kevingo** [comment]
@Psycho7 That will be great. Any PR will be great !! Thanks.

**Pull request merged**
