### PR TITLE
Add 'grep . *' oneliner trick for high-level scan of a directory

### PR DESCRIPTION
**Pull request by adamm**
One neat CLI trick which I find useful :)

### CODE REVIEW

**Comment by perryclarke** [comment]
How is this different from `cat *` and why is that useful?

**Comment by bmedicke** [comment]
Grep prepends the line with filename. As for when it's useful the commit mentions directories filled with config files (never used it myself though).

**Comment by MichaelCorona** [comment]
Grep as opposed to cat will also handle binary files and not clog the console with a bunch of garbage.

**Comment by adamm** [comment]
It's also useful for a directory with multiple config files each contain multiple lines.
Where each line is prefixed by the file name.

For example, run it in /etc/logrotate.d:
http://pastebin.com/az18G3wU

(Wow. I have ppp installed?! :)

**Comment by jlevy** [comment]
I've often used `head -1000 *` but this is better. :+1: Thanks.

**Pull request merged**
