### PR TITLE
ru: Fix typo

### PR DESCRIPTION
**Pull request by isvforall**
The word "частоиспользуемые" does not exist

### CODE REVIEW

**Comment by idvoretskyi** [comment]
LGTM.

**Comment by jlevy** [comment]
Thanks! @olegberman review on this and #439?

**Comment by BioQwer** [comment]
LGTM.
@jlevy merge it plz, this is one word correction right.

**Comment by jlevy** [comment]
Merging given it's small and reviewed twice. @olegberman of course rewrite if needed!

**Comment by jlevy** [comment]
Thanks @BioQwer

**Pull request merged**
