### PR TITLE
zh-hant: Translate the section "Windows only"

### PR DESCRIPTION
**Pull request by gaga5lala**

### CODE REVIEW

**Comment by Psycho7** [comment]
@kevingo Have a check?

**Comment by kevingo** [comment]
@Psycho7 sure, I will check later.

**Comment by jimpire** [comment]
I have a cool Baytech power strip with 21 manageable outlets. Suppose I
should look into hooking it up...

**Comment by jimpire** [comment]
…but I like the Wemo idea too. Never heard of the 'til now. ;)

**Comment by kevingo** [comment]
@Psycho7 LGTM 👍

**Comment by jlevy** [comment]
Thanks, everyone!

**Pull request merged**
