### PR TITLE
zh: add several command line tools for OS X only section

### PR DESCRIPTION
**Pull request by colinwjd**
At the same time, change some ':' to '：' so it can keep in line with the others.

### CODE REVIEW

**Comment by Psycho7** [comment]
@jlevy okay to merge
Thanks @colinwjd

**Comment by wyf88** [comment]
@Psycho7 But it is said that 
> Translations follow the content of the original.

**Comment by Psycho7** [comment]
@wyf88 That's fault. Thank your for pointing it out.
I didn't realize there were some new content.

@colinwjd  How about you change the topic of this PR to changing  ':' to '：' ? And commit another PR to add new content at English version first?

**Comment by colinwjd** [comment]
@wyf88 @Psycho7 thank you for reminding me.

**Pull request closed without merging**
