### PR TITLE
Added bash shortcuts in MacOS for moving back/forward one word

### PR DESCRIPTION
**Pull request by abednarik**

### CODE REVIEW

**Comment by NewAlexandria** [comment]
This is not bad, but I would prefer an easier integration of [the modifier+arrow key movements](http://superuser.com/a/357394/69570)

**Comment by alejandrobednarik-olx** [comment]
Agree with you.  I just added the default one's.
Also using the default  bash version  in Mac is pretty odd.  I can add a single reference to brew and bash update.

**Comment by dougharris** [comment]
Perhaps this doc needs a "special stuff for OS X" command line, starting with:

* Open Terminal preferences
* From the Profiles pane, click the Keyboard options
* Check "Use Option as Meta Key" 

This allows mac users to use `option+` wherever the docs say `alt+`

**Comment by abednarik** [comment]
Looks like this is not really helpful. Closing.

Cheers.

**Pull request closed without merging**
