### PR TITLE
ru: Minor fixes

### PR DESCRIPTION
**Pull request by DDyst**
- added some typo fix and punctuation corrections

### CODE REVIEW

**Review by idvoretskyi — APPROVED** [review]
LGTM

**Review by timacs — APPROVED** [review]
Wow, thanks for the proof reading of such amount. LGTM.

**Comment by jlevy** [comment]
👍 yes, awesome, thanks @DDyst @idvoretskyi @tim-teufel . 
@olegberman can you give a quick look too since you're ru maintainer?

**Comment by olegberman** [comment]
@jlevy  Sure thing. This can definitely be merged!

**Comment by jlevy** [comment]
👍 Thank you @DDyst @idvoretskyi @olegberman !

**Pull request merged**
