### PR TITLE
Added mmv

### PR DESCRIPTION
**Pull request by katgironpe**

### CODE REVIEW

**Comment by NewAlexandria** [comment]
That's really interesting.  Not a standard lib, but interesting

**Comment by katgironpe** [comment]
@NewAlexandria there are a few in the section that require user to install the package including `aws-cli` so I think this is the right section. Installation of the `aws-cli` and `mmv` differs for every Unix distro. A few commands like `lynx` do not work on OS X. We should probably have installation notes on another file and link to that. Good reference since I could not find any on the web that does so for every Unix distribution.

**Comment by Hunter-Github** [comment]
Looks like this utility kind of fell out of development. https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=mmv;dist=unstable

**Comment by katgironpe** [comment]
Last message/ patch was in 2012 but still usable https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=149873  Could be opportunity for someone to take over that. For now, I will close this PR.

**Comment by jlevy** [comment]
`rename` (better known) and [`repren`](https://github.com/jlevy/repren) (not well known but more flexible) are both listed, so I think this is covered reasonably without mmv, though would be good to hear of pros/cons of mmv if you have them. (Feel free to file requests for these features as issues on repren, too, as I maintain it.)

**Pull request closed without merging**
