### PR TITLE
ru: Major improvements in Russian version

### PR DESCRIPTION
**Pull request by olegberman**
A work by several contributors. I'm not sure how to go about this, but I'm thinking this needs to be merged before any other PR's with typo fixes as this probably covers most of them. 

Thanks

### CODE REVIEW

**Comment by jlevy** [comment]
Cool, thanks @olegberman and all!

Looks like lots of changes have come in at once. :(

Can you resolve conflicts so this one can go through, and either merge in #176 #177 #178 here or comment on them if they are already taken care of?

**Comment by olegberman** [comment]
Sure, will do @jlevy

**Comment by olegberman** [comment]
Done. Thanks @sn00p, @osmero and others! Now this is looking really good! 👍

**Comment by jlevy** [comment]
:+1: Thanks @olegberman and all!
Going forward, I'll assume ru PRs are in progress until you say "@jlevy ready to merge". :)

**Pull request merged**
