### PR TITLE
Add contribution guidelines.

### PR DESCRIPTION
**Pull request by jlevy**
Being more explicit about some of this may help streamline and encourage contributions, as more languages are being added and I've gotten a few process questions. Hope this helps.

### CODE REVIEW

**Comment by jlevy** [comment]
Any feedback from contributors, especially translation maintainers, on this?
@ceoaliongroo @doublemarket @Ungsik-Yun @niltonvasques @olegberman @peterkokot @Psycho7 @stepan0904 @francescomalatesta

Also in-progress translators @lsrom @ahmetshen-us

**Comment by jlevy** [comment]
Thanks in advance for giving thoughts on if you are good with this.

**Comment by francescomalatesta** [comment]
Added some suggestions in #338 :)

**Comment by doublemarket** [comment]
Nice document!

**Comment by jlevy** [comment]
@elacheche -- hope this formalizes what we discussed.

**Comment by jlevy** [comment]
All -- I've gone ahead and merged but please comment further if you have feedback on how it could be better. Thanks so much especially to the translation maintainers!

**Comment by elacheche** [comment]
@jlevy YES! :D 
I'll read it in details this weekend, and start contributing based on this guide line :)

**Comment by peterkokot** [comment]
:+1: This document will come in handy. Thanks @jlevy

**Comment by Psycho7** [comment]
Nice document :+1: 
But should it be translated too?

**Comment by jlevy** [comment]
@Psycho7 In principle it would be nice, but I think that would be too much overhead to manage this doc too in 12+ languages for every change. Obviously many readers speak no English, but I believe most contributors to the translations need to speak a little English, since we don't want the translations to diverge from the English original.

**Pull request merged**
