### PR TITLE
Update authors/stats.

### PR DESCRIPTION
**Pull request by jlevy**

### CODE REVIEW

**Comment by jlevy** [comment]
@dmytro you're now listed, with uk maintainer role.
@idvoretskyi @lmount @w169q169 @wyf88 welcome to the list too!
Thanks all! :)

**Comment by dmytro** [comment]
Thank you.

**Comment by w169q169** [comment]
Thank you.

**Comment by idvoretskyi** [comment]
@jlevy thank you!

**Comment by lmount** [comment]
Thanks :-)

**Pull request merged**
