### PR TITLE
Add cheat sheet to commands

### PR DESCRIPTION
**Pull request by randombenj**
The [cheat.sh](https://github.com/chubin/cheat.sh) is a handy helper which I use quite often, because sometimes you don't want to read a whole man page and only see how to use command xyz again.
Additionally you don't have to install anything which I think is quite neat.

### CODE REVIEW

**Comment by jlevy** [comment]
Good addition. Thanks!

**Comment by CharlieStras** [comment]
Seems that there is nothing in [cheat.sh/command](http://cheat.sh/command), is it OK to change the address to [cheat.sh/bash](http://cheat.sh/bash)?

**Comment by randombenj** [comment]
Thanks for merging 🍻
@CharlieStras shure it could be changed to `curl cheat.sh/bash` but I thaught I'd stick to the same formating as `type command`.

**Comment by CharlieStras** [comment]
I’m sorry for misunderstanding the word “command” :D

**Comment by jlevy** [comment]
yeah would be clearer with italics or similar. :/

**Pull request merged**
