### PR TITLE
Markdown enhancement

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by jlevy** [comment]
Thanks! What's the reason some are bash and some sh?

**Comment by kargakis** [comment]
As I went through the different stanzas, I labeled as sh those that didn't contain any bash-specific commands, though I just noticed that some slipped to sh (L243 and L248). No big deal since sh markdown is not different than bash.

**Comment by kargakis** [comment]
> I labeled as sh those that didn't contain any bash-specific commands, though I just noticed that some slipped to sh (L243 and L248).

Hmm, I always thought that find and xargs were bash-specific commands. They are not. Nevermind quoted text.

**Comment by jlevy** [comment]
Is the Markdown coloring the same in any case? If so I'll just make all bash.

**Comment by kargakis** [comment]
> Is the Markdown coloring the same in any case? If so I'll just make all bash.

I think it is. Go ahead and make the change as I shouldn't have used sh in the first place.

**Pull request merged**
