### PR TITLE
ru: Typo fix

### PR DESCRIPTION
**Pull request by SemenMartynov**
Small typo fix in Russian version.

### CODE REVIEW

**Comment by tim-teufel** [comment]
OK to merge (but I'm not the maintainer of the Russian translation).

**Comment by jlevy** [comment]
Thanks @SemenMartynov and @tim-teufel !
@olegberman review?

**Comment by idvoretskyi** [comment]
LGTM.

**Comment by olegberman** [comment]
Approve.

**Comment by BioQwer** [comment]
@jlevy merge it plz, this is correction definitely right.

**Comment by jlevy** [comment]
👍 💯

**Pull request merged**
