### PR TITLE
Add commands for creating large dummy files

### PR DESCRIPTION
**Pull request by mkwardakov**
Because `dd` is not so effective. Actually don't know how common is the task.

### CODE REVIEW

**Comment by jlevy** [comment]
Sure, I'm up for including these. My only request would be let's move it to one line to save space?

- To create empty files quickly, use `truncate` (creates a [sparse file](https://en.wikipedia.org/wiki/Sparse_file)), `fallocate` (ext4, xfs, btrfs and ocfs2 filesystems), `xfs_mkfile` (almost any filesystems, comes in xfsprogs package), or`mkfile` (for Unix-like systems like Solaris, Mac OS).

**Comment by jlevy** [comment]
@Lakshmipathi since you're a filesystem expert, would you care to review? :)

**Comment by Lakshmipathi** [comment]
sure, patch looks good :+1:   - not an FS expert though, more like FS fanatic :)

**Comment by mkwardakov** [comment]
@jlevy rebased my branch and rewrote changes as oneliner

**Comment by jlevy** [comment]
👍 Thanks @mkwardakov @Lakshmipathi !

**Pull request merged**
