### PR TITLE
brace expansion example.

### PR DESCRIPTION
**Pull request by sirsgriffin**

### CODE REVIEW

**Comment by jheryson** [comment]
Requesting for Managing Deploy Key

**Comment by jheryson** [comment]
Sir since i started to learn how to use a code i'm only using my  adroid
phone coz i don't have a money to buy some computer.

Can i also use my adroid phone to deploy? If yes what apps can i use? Sorry
if I'm noob i did't study or go to school to learn about this i just learn
this thing i just learn this in my own way.

Thanks

**Comment by jlevy** [comment]
:+1: Thanks!

**Comment by jheryson** [comment]
Your friends are chatting on Talkray                                
                     = Your Friends are Chatting on Talkray =

               Don't miss out. See what everyone is talking about. Download
Talkray now to chat with your friends around the world.

                Get Talkray <http://mandrillapp.com/track/click/30879081/talkray.co?p=eyJzIjoiR2E0SlE2d3pvVzdLY0tfZXJkdENXTmNnR0VVIiwidiI6MSwicCI6IntcInVcIjozMDg3OTA4MSxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvdGFsa3JheS5jb1xcXC90bWlcIixcImlkXCI6XCI4Y2ZlZDE3ZWExMjQ0Y2JkYjBkYWM2ODAxZjcyMzYxNVwiLFwidXJsX2lkc1wiOltcImFkYzMyMWZjMWM0YTQ1ZDFmYzVjNWIzMjJjYzc5YTBiZTk4NzIxMWFcIl19In0>                        
                 Call your Talkray friends from anywhere in the world,
always at no cost. Experience the clearest and fastest calls, with groups
up to 25.                          Chat and message your friends from
anywhere. Send Photos, Videos, Voice Messages, and more.                   
        Send from thousands of stickers available only on Talkray. You can
even create your own stickers to send to your friends.               Chat
on Talkray <http://mandrillapp.com/track/click/30879081/talkray.co?p=eyJzIjoiR2E0SlE2d3pvVzdLY0tfZXJkdENXTmNnR0VVIiwidiI6MSwicCI6IntcInVcIjozMDg3OTA4MSxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvdGFsa3JheS5jb1xcXC90bWlcIixcImlkXCI6XCI4Y2ZlZDE3ZWExMjQ0Y2JkYjBkYWM2ODAxZjcyMzYxNVwiLFwidXJsX2lkc1wiOltcImFkYzMyMWZjMWM0YTQ1ZDFmYzVjNWIzMjJjYzc5YTBiZTk4NzIxMWFcIl19In0>                         Copyright ©
2016 TiKL, Inc. All Rights Reserved. 
 
101 Redwood Shores Parkway • Redwood City, CA 94065 USA





This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
unsubscribe from this list (http://mandrillapp.com/track/unsub.php?u=30879081&id=8cfed17ea1244cbdb0dac6801f723615.onP5fYwLVT3ep9KQrn2Fm9vgzbs%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dreply%252B00c604395e9c1949f4454867d9efb4b10b6ce0621bf3fdd592cf0000000111a209d492a169ce0566134d%2540reply.github.com)

**Pull request merged**
