### PR TITLE
Arabic version

### PR DESCRIPTION
**Pull request by elacheche**
I know that this will be very hard to translate, but someone should do it :)
If you're an Arabic and ready this comment please contribute and help me translate the whole thing :)

### CODE REVIEW

**Comment by elacheche** [comment]
@jlevy Can you review this please?

**Comment by jlevy** [comment]
Yes, new translations are always welcome, assuming you are a native speaker and write well in the language. :) Will you also be able to maintain/review issues on it?

Just fork this repo and add commits for the translation, and create a PR. You can share the PR with friends and get feedback, which helps. If you want others to help write the translation, have them fork your repo and merge into your repo.

Once there is a full translation that's been reviewed by at least one other person, would be glad to merge it in.

Thanks for starting this!

**Comment by elacheche** [comment]
OK!
I understand how this work now :+1: 

Yes, I'm a native speaker, and we have community that contribute only in FOSS projects Translation.

I'll ask friends to contribute to my fork, and ask someone else to review it with me then I'll create new PR once the whole file is translated.

Thanks  @jlevy

**Comment by jlevy** [comment]
Great! Thank you for the work bringing this to Arabic speakers.

**Pull request closed without merging**
