### PR TITLE
typo （修改错别字）

### PR DESCRIPTION
**Pull request by picasso250**
会时 sort ==> 会使 sort

### CODE REVIEW

**Comment by jlevy** [comment]
Thank you!
@Psycho7 review?

**Comment by RoyLING** [comment]
As a Chinese, this typo fix can be merged.

**Comment by jlevy** [comment]
:+1: Thanks.
@Psycho7 fyi -- hope you can keep helping review.

**Comment by Psycho7** [comment]
@jlevy Sorry for my absence. I have been preparing my GRE test these days. It's not easy for a non-native English speaker :( 
I won't miss these work anymore. I promise

**Comment by jlevy** [comment]
@Psycho7 Great. Thanks as always for the help.

**Pull request merged**
