### PR TITLE
ru: Polish README-ru.md

### PR DESCRIPTION
**Pull request by zelark**
Some fixes in the disclaimer.

### CODE REVIEW

**Comment by zelark** [comment]
@tim-teufel, thank you, I fixed it.

**Comment by idvoretskyi** [comment]
LGTM.

**Comment by jlevy** [comment]
@olegberman are you still able to review?
@tim-teufel if you have reviewed closely and are a native speaker, let me know, and I'll count your review as official. :)

**Comment by tim-teufel** [comment]
Yes, this PR is fine, and I'm a native speaker.

**Comment by olegberman** [comment]
This is good, merge it.

**Comment by jlevy** [comment]
Thanks @zelark @tim-teufel @olegberman !

**Pull request merged**
